### ISSUE TITLE
Backup.zip is a directory not a archive

### ISSUE THREAD

**Issue by dvdcd** [ZombieStriker/ServerRestorer#10]
I'm getting this error with the latest version of the plugin on 1.15.1
My config is stock except the backup name was changed to backup without the date.
In my server files the folders in backups are folders and not zips like it's expecting. 
I'm running spigot git-Spigot-2ee05fe-d31f05f (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT) with Pebblehost's custom version of multimc
> `16.01 01:46:48 [Server] Server thread/INFO [ServerRestorer] Starting to save directory. Please wait.
16.01 01:46:48 [PebbleHost] dvdcd ran command: sr save
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN java.io.FileNotFoundException: /backups/Backup.zip (Is a directory)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at java.io.FileOutputStream.open0(Native Method)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at java.io.FileOutputStream.open(FileOutputStream.java:270)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at me.zombie_striker.sr.Main.zipFolder(Main.java:586)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at me.zombie_striker.sr.Main$4.run(Main.java:399)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16.01 01:46:51 [Server] Craft Scheduler Thread - 2/WARN at java.lang.Thread.run(Thread.java:748)`

**Comment by ZombieStriker** [comment]
This issue should be fixed in the most recent update (v1.0.28)
