### ISSUE TITLE
Very Good Backup But... Spam...

### ISSUE THREAD

**Issue by TheCiROMG** [ZombieStriker/ServerRestorer#28]
![image](https://user-images.githubusercontent.com/61605643/88999317-8e3fe400-d2ca-11ea-859f-d31c8fd9a8e2.png)

The users read this logs

**Comment by hydridity** [comment]
I agree, it's not problem having it to log it to the console (maybe some sort of backup session log file would be nice), but it's get spammed to user chat aswell (Not sure if only to op user or also non op user)

**Comment by TheCiROMG** [comment]
Not only in the console, also in the game (all users) but they already corrected it in the update (last)
