### ISSUE TITLE
[QUESTION] How to set max backups

### ISSUE THREAD

**Issue by srnyx** [ZombieStriker/ServerRestorer#39]
> Backup limits: If you're limited on space, you can configure limits to the amount of backups that are stored.

How?

**Comment by sjingoi** [comment]
In config.yml, change MaxSaveSize or MaxFileSaved

**Comment by srnyx** [comment]
> In config.yml, change MaxSaveSize or MaxFileSaved

Thanks!

**Comment by srnyx** [comment]
Forgot to ask, will it delete the oldest backups and replace them with new ones? Or will it just stop creating backups when it reaches max?

**Comment by sjingoi** [comment]
Yep it will delete the oldest one once it reaches the max
